name: Bug report
description: Create a bug report to help us improve
title: "bug(<scope>): <title starting with lowercase letter>"
labels: ["community", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? You're welcome to [![GitHub Discussions](https://img.shields.io/badge/chat-discussions-blue.svg?style=flat-square)](https://github.com/Checkmarx/checkmarx-kiro-powers/discussions)
        
        **Please make sure to:**
        - Describe in details what the problem is
        - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG` if applicable)
        - Attach the scanned sample files, anonymize the data if the original file cannot be provided
        - When attaching files to the issue make sure they are properly formatted
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Which results are expected?
      placeholder: Describe what you expected to happen
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Formatted logs and samples helps us to better understand the issue
      placeholder: Describe what actually happened
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Problem
      description: Command line arguments and flags used
      placeholder: |
        1. step 1
        2. step 2
        3. step 3
    validations:
      required: true
  
  - type: textarea
    id: specifications
    attributes:
      label: Specifications
      description: N/A if not applicable
      placeholder: |
        - Version: 
        - Platform: 
        - Subsystem:
    validations:
      required: false
  
  - type: checkboxes
    id: checks
    attributes:
      label: Confirmation
      options:
        - label: This is not a security vulnerability report (use SECURITY.md for those).
          required: true
